apiVersion: v1
kind: Service
metadata:
  name: service-hellok8s-clusterip
spec:
  type: ClusterIP
  selector:
    # 这里声明哪些是被 selector 选中的 Pod
    app: angular-k8s
  ports:
  - port: 4000
    targetPort: 80
